[package]
authors = ["Daniel García Moreno <danigm@wadobo.com>"]
description = """
Library to support the reading of epub files.
"""
exclude = ["test.epub"]
keywords = [
    "epub",
    "ebook",
]
license = "GPL-3.0"
name = "epub"
repository = "https://github.com/danigm/epub-rs.git"
version = "1.2.1"
edition = "2018"

[dependencies]
failure = "0.1.6"
regex = "1.3.1"
xml-rs = "0.8.0"
zip = "0.5.3"
percent-encoding = "2.1.0"
